diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
credential.helper=manager
core.editor="C:\Users\mathe\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait
user.email=axe@outlook.com.br
user.name=Matheus
gui.recentrepo=C:/Users/mathe/GabrielRezende
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/silveriosepulveda/gabrielrezende.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
remote.segundo.url=https://github.com/silveriosepulveda/gabeirlrezende
remote.segundo.fetch=+refs/heads/*:refs/remotes/segundo/*
remote.sitegabriel.url=https://github.com/haganashh/Teste.git
remote.sitegabriel.fetch=+refs/heads/*:refs/remotes/sitegabriel/*
remote.gabriel.url=https://github.com/silveriosepulveda/gabrielrezende.git
remote.gabriel.fetch=+refs/heads/*:refs/remotes/gabriel/*
gui.wmstate=normal
gui.geometry=893x435+208+208 175 196
